### ISSUE TITLE
ViewHelper Template Path

### ISSUE THREAD

**Issue by prajuritbs** [digicademy/category_selector#5]
Hi,

i couldn't change the templaterootpath for the ViewHelper Template.

Is it possible to change, so that i can outsource this in my fileadmin.

This is working for Partials and Templates:

plugin.tx_categoryselector {
   view{
     templateRootPaths >
     templateRootPaths{
        0 = EXT:category_selector/Resources/Private/Templates/
        1 = fileadmin/template/ext/categoryselector/Templates/
     }
     partialRootPaths >
     partialRootPaths{
        0 = EXT:category_selector/Resources/Private/Partials/
        1 = fileadmin/template/ext/categoryselector/Partials/
     }
   }  
}

But this isn't working for the ViewHelper:
plugin.tx_categoryselector.view.widget.ADWLM\CategorySelector\ViewHelpers\Widget\CategoryfilterViewHelper.templateRootPath = Some/path

**Comment by metacontext** [comment]
Hi there,

thanks for your question. The reason (according to the snippet above) is that the widget's templateRootPath is not configured in the correct namespace. It should not be configured for  "plugin.tx_categoryselector" but the namespace of the plugin that generates your list of objects. 
If this was the news extension for example, the correct TypoScript would be:

plugin.tx_news.view.widget.ADWLM\CategorySelector\ViewHelpers\Widget\CategoryfilterViewHelper.templateRootPath = Some/path

**Comment by veraju** [comment]
Thanks a lot! Works fine :-)

**Comment by metacontext** [comment]
Perfect. Thanks for reporting, closing the issue.
